doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Users/Entity'
                prefix: 'App\Domain\Users\Entity\User'
                alias: User
            News:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/News/Entity'
                prefix: 'App\Domain\News\Entity\News'
                alias: News
            Event:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Events/Entity'
                prefix: 'App\Domain\Events\Entity\Event'
                alias: Event
