security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
        user:
            id: App\Infrastructure\Security\UserProvider
    encoders:
        App\Domain\Users\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/v1/(login|register)
            anonymous: true
        туцы:
            pattern: ^/v1/news
            anonymous: true
        app:
            pattern: ^/v1/.*
            anonymous: false
            stateless: true
            provider: user
            guard:
                authenticators:
                    - App\Infrastructure\Security\TokenAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/v1/register, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/login, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/news, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/admin, methods: [POST, GET, PATCH, DELETE], roles: ROLE_ADMIN }
