version: '3'
services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      TIMEZONE: Europe/Moscow
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_enable=1
      TZ: Europe/Moscow
    volumes:
      - './docker/php/php.ini:/usr/local/etc/php/php.ini'
      - './:/var/www/app:cached'
    working_dir: /var/www/app
  nginx:
    image: nginx
    environment:
      TZ: Europe/Moscow
    depends_on:
      - php
    volumes:
      - './app/:/var/www/app/app:cached'
      - './docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
  mysql:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: sf-racing
      MYSQL_DATABASE: sf-racing
      MYSQL_USER: sf-racing
      MYSQL_PASSWORD: sf-racing
      TZ: Europe/Moscow
